extends Node

var loc_1 : LocationData = preload("res://Data/Location/1.tres")
var loc_2 : LocationData = preload("res://Data/Location/2.tres")
var loc_3 : LocationData = preload("res://Data/Location/3.tres")
var loc_4 : LocationData = preload("res://Data/Location/4.tres")
var loc_5 : LocationData = preload("res://Data/Location/5.tres")
var loc_6 : LocationData = preload("res://Data/Location/6.tres")
var loc_7 : LocationData = preload("res://Data/Location/7.tres")
var loc_8 : LocationData = preload("res://Data/Location/8.tres")
var loc_9 : LocationData = preload("res://Data/Location/9.tres")
var loc_10 : LocationData = preload("res://Data/Location/10.tres")
var loc_11 : LocationData = preload("res://Data/Location/11.tres")
var loc_12 : LocationData = preload("res://Data/Location/12.tres")
var loc_13 : LocationData = preload("res://Data/Location/13.tres")
var loc_14 : LocationData = preload("res://Data/Location/14.tres")
var loc_15 : LocationData = preload("res://Data/Location/15.tres")
var loc_16 : LocationData = preload("res://Data/Location/16.tres")
var loc_17 : LocationData = preload("res://Data/Location/17.tres")
var loc_18 : LocationData = preload("res://Data/Location/18.tres")
var loc_19 : LocationData = preload("res://Data/Location/19.tres")
var loc_20 : LocationData = preload("res://Data/Location/20.tres")
var loc_21 : LocationData = preload("res://Data/Location/21.tres")
var loc_22 : LocationData = preload("res://Data/Location/22.tres")
var loc_23 : LocationData = preload("res://Data/Location/23.tres")
var loc_24 : LocationData = preload("res://Data/Location/24.tres")
var loc_25 : LocationData = preload("res://Data/Location/25.tres")
var loc_26 : LocationData = preload("res://Data/Location/26.tres")
var loc_27 : LocationData = preload("res://Data/Location/27.tres")
var loc_28 : LocationData = preload("res://Data/Location/28.tres")
var loc_29 : LocationData = preload("res://Data/Location/29.tres")
var loc_30 : LocationData = preload("res://Data/Location/30.tres")
var loc_31 : LocationData = preload("res://Data/Location/31.tres")
var loc_32 : LocationData = preload("res://Data/Location/32.tres")
var loc_33 : LocationData = preload("res://Data/Location/33.tres")
var loc_34 : LocationData = preload("res://Data/Location/34.tres")
var loc_35 : LocationData = preload("res://Data/Location/35.tres")
var loc_36 : LocationData = preload("res://Data/Location/36.tres")


func get_by_index(index : int) -> LocationData:
	return get("loc_%s" % index)
